# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd backend/src/test/bash
        source setup
        bash scripts/ubuntu_startup
        cd ../../..
        #cd ../backend
        mvn package spring-boot:start
        cd src/test/bash
        #cd ../http
        init users
        source sin user1 password
        init tasks
        tester enable
        cd ../../..
        #cd ../backend
        mvn spring-boot:stop
